/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "FreeRTOS.h"
#include "task.h"
#include "FreeRTOSConfig.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vUartPeriodicTask(void *pvParam)
{
	char str[32];
	while(1) {
		UartGets(str);
		strupr(str);
		UartPuts(str);
	}
	//portTickType wakeTime = xTaskGetTickCount();
	/*while(1)
	{
		//led_toggle();
		vTaskDelayUntil(&wakeTime, 1000 / portTICK_RATE_MS);
	}*/
	vTaskDelete(NULL);
}

int main(void)
{

	BaseType_t ret;
	UartInit(BAUD_9600);
	ret=xTaskCreate(vUartPeriodicTask,"UartPuts",configMINIMAL_STACK_SIZE,NULL,2,NULL);
	if(ret!=pdTRUE)
	//UartPuts("Enter Strings...\r\n");
		while(1);
	vTaskStartScheduler();
	while(1);
	return 0;
}
